### PR TITLE
Update rotation of people

### PR DESCRIPTION
**Pull request by lbarcziova**
We have the same number of people and roles,
therefore do not pick randomly, only rotate the order.

### CODE REVIEW

**Review by nforro — APPROVED** [review]

**Review by lachmanfrantisek — COMMENTED** [review]
What about supporting both ways depending on the number of people in the team so we don't need to change anything once we get more people?

**Review by majamassarini — APPROVED** [review]
🙏

**Comment by lbarcziova** [comment]
> What about supporting both ways depending on the number of people in the team so we don't need to change anything once we get more people? 

since we always need to do the manual addition of the person, I did not find it worth spending more time on this...but I can update it

**Review by lachmanfrantisek — APPROVED** [review]
>  since we always need to do the manual addition of the person, I did not find it worth spending more time on this...but I can update it

Thanks! At least we don't need to think about the implementation and just edit the names.

**Pull request merged**
